config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :customers, only: [:index, :show]
  resources :tweets, only: [:index]

  mount Sidekiq::Web => '/monitor'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :tweets, dependent: :destroy, autosave: true

  before_create :set_code

  private

    def set_code
      self.code = generate_code unless code
    end

    def generate_code
      loop do
        random_code = SecureRandom.hex(4)
        break random_code unless Customer.where(code: random_code).exists?
      end
    end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :customer, counter_cache: true

  def find_customer_code
     params = CGI.parse(URI.parse(expanded_url).query)
     params['code'].first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @customers_count = Customer.count
    @tweets_count = Tweet.count
    @plot_data = Tweet.where('created_at > ?', 30.days.ago).group('DATE(created_at)').count.collect { |date, count| { date: date, tweets: count } }.to_json
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customers/index.slim
h1.page-header Customers

.panel.panel-default
  .panel-body
    table#customers
      thead
        tr
          th ID
          th Twitter handle
          th Ref. code
          th Last tweet
      tbody
        - @customers.each do |customer|
          tr
            td= link_to customer.id, customer_path(customer)
            td= customer.tweets.last&.twitter_user_handle
            td= customer.code
            td= time_tag customer.tweets.last&.created_at

app/views/customers/show.slim
h1.page-header Customer ##{@customer.id}

= render 'tweets/index', tweets: @customer.tweets

app/views/home/customers.slim
h1.page-header Customers

.panel.panel-default
  .panel-body
    table#customers
      thead
        tr
          th ID
          th Twitter handle
          th Ref. code
      tbody
        - @customers.each do |customer|
          tr
            td= customer.id
            td= customer.tweets.last&.twitter_user_handle
            td= customer.code

app/views/home/index.slim
h1.page-header Dashboard

.row
  .col-lg-3.col-md-6
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-users.fa-5x
          .col-xs-9.text-right
            .huge= @customers_count
            div Customers

      = link_to customers_path do
        .panel-footer
          span.pull-left View Details
          span.pull-right
            i.fa.fa-arrow-circle-right
          .clearfix

  .col-lg-3.col-md-6
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-twitter.fa-5x
          .col-xs-9.text-right
            .huge= @tweets_count
            div Tweets

      = link_to tweets_path do
        .panel-footer
          span.pull-left View Details
          span.pull-right
            i.fa.fa-arrow-circle-right
          .clearfix

#dashboard-chart data-points=(@plot_data)

app/views/layouts/application.slim
doctype 5
html lang='en'
  head
    title Dashboard | Twitfer

    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body class=page_class
    #wrapper
      nav.navbar.navbar-default.navbar-static-top role='navigation' style='margin-bottom: 0'
        .navbar-header
          button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-collapse'
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href='/' Twitfer

        .navbar-default.sidebar role='navigation'
          .sidebar-nav.navbar-collapse
            ul#side-menu.nav
              li
                a href='/'
                  i.fa.fa-dashboard.fa-fw
                  |  Dashboard
              li
                a href=customers_path
                  i.fa.fa-user.fa-fw
                  |  Customers
              li
                a href=tweets_path
                  i.fa.fa-user.fa-fw
                  |  Tweets
              li
                a href=sidekiq_web_path target='_blank'
                  i.fa.fa-tasks.fa-fw
                  |  Monitor

      #page-wrapper
        .container-fluid
          = yield

    = javascript_initialization

app/views/tweets/_index.slim
.panel.panel-default
  .panel-body
    table#tweets
      thead
        tr
          th ID
          th Tweet id
          th Twitter user id
          th Twitter user handle
          th Text
          th Created at
      tbody
        - tweets.each do |tweet|
          tr
            td= tweet.id
            td= tweet.tweet_id
            td= tweet.twitter_user_id
            td= tweet.twitter_user_handle
            td= tweet.text
            td= time_tag tweet.created_at

app/views/tweets/index.slim
h1.page-header Tweets

= render 'tweets/index', tweets: @tweets